version: "3.9"
services:
  api:
    image: eucalyptus-backend:${IMAGE_VERSION:-latest}
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=0.0.0.0:4000
      - DB_DSN=postgresql://app:uJyzCW9dTM1X@ep-empty-mouse-a1osmng6.ap-southeast-1.aws.neon.tech/eucalyptus?sslmode=require
      - REDISCLOUD_URL=redis:6379
      - SMTP_HOST=sandbox.smtp.mailtrap.io
      - SMTP_USERNAME=47a0bd37235fa1
      - SMTP_PASSWORD=9a0ad4d8cdadb7
    depends_on:
      # - postgres
      - redis
      # - migrate
  redis:
    image: redis:7.2-alpine
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save  20  1 --loglevel warning
    volumes:
      - ./docker/cache:/data
  # postgres:
  #   image: postgres:16.2-alpine
  #   container_name: db
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=secret
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db:/var/lib/postgresql/data
  # migrate:
  #   image: migrate/migrate
  #   volumes:
  #     - ./migrations:/migrations
  #   command: ["-path", "/migrations", "-database",  "postgres://root:secret@postgres:5432/eucalyptus?sslmode=disable", "up"]
  #   depends_on:
  #     - postgres
  #   links: 
  #     - postgres

volumes:
  db:
    # mailpit:
    # image: axllent/mailpit
    # container_name: eucalyptus-mailserver
    # restart: always
    # volumes:
    # - ./docker/smtp/data:/data
    # - ./docker/smtp/certs:/certs
    # ports:
    # - 8025:8025
    # - 1025:1025
    # environment:
    # MP_MAX_MESSAGES: 5000
    # MP_DATA_FILE: /data/mailpit.db
    # MP_SMTP_AUTH_ACCEPT_ANY:
    # MP_SMTP_TLS_CERT: certs/mailserver.crt
    # MP_SMTP_TLS_KEY: certs/mailserver.key
    # MP_SMTP_TLS_REQUIRED:
