// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDoctorById(ctx context.Context, doctorID int32) (Doctor, error)
	GetHealthRecordByRecordId(ctx context.Context, recordID int32) (HealthRecord, error)
	GetHealthRecordsByPatientId(ctx context.Context, patientID pgtype.Int4) ([]HealthRecord, error)
	GetHospitalByHospitalId(ctx context.Context, hospitalID int32) (Hospital, error)
	GetMedicationsByPrescriptionId(ctx context.Context, prescriptionID pgtype.Int4) ([]Medication, error)
	GetPrescriptionsByPatientId(ctx context.Context, patientID pgtype.Int4) ([]Prescription, error)
	GetProfileByUserId(ctx context.Context, userID pgtype.Int4) (Profile, error)
	GetUsersByUsername(ctx context.Context, userID int32) (AppUser, error)
	InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error
	InsertHealthRecord(ctx context.Context, arg InsertHealthRecordParams) error
	InsertMedication(ctx context.Context, arg InsertMedicationParams) error
	InsertPrescription(ctx context.Context, arg InsertPrescriptionParams) error
	UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error
	UpdateHealthRecord(ctx context.Context, arg UpdateHealthRecordParams) error
	UpdateMedication(ctx context.Context, arg UpdateMedicationParams) error
	UpdatePrescription(ctx context.Context, arg UpdatePrescriptionParams) error
}

var _ Querier = (*Queries)(nil)
