// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHealthRecord = `-- name: GetHealthRecord :one
SELECT record_id, patient_id, treatment_history, medical_directives, vaccination_history, allergies, family_medical_history, social_history, review_of_systems, physical_examinations, created_at, updated_at
FROM health_record
WHERE patient_id = $1
`

func (q *Queries) GetHealthRecord(ctx context.Context, patientID pgtype.Int4) (HealthRecord, error) {
	row := q.db.QueryRow(ctx, getHealthRecord, patientID)
	var i HealthRecord
	err := row.Scan(
		&i.RecordID,
		&i.PatientID,
		&i.TreatmentHistory,
		&i.MedicalDirectives,
		&i.VaccinationHistory,
		&i.Allergies,
		&i.FamilyMedicalHistory,
		&i.SocialHistory,
		&i.ReviewOfSystems,
		&i.PhysicalExaminations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
